#!/bin/env python

# Copyright (c) 2014 Caitlin Potter and Contributors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#  * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import sys,os,re
from waflib import Logs
SUBDIRS=['Text','Sniffer','Buffer']

def options(ctx):
	ctx.add_option('--compact',dest='compact',
		           help='Show compacted test output',
		           action='store_true', default=False)

def configure(ctx):
	pass

def build(ctx):
	lib=[]
	#ctx.options.all_tests = True
	features=['cxx','cxxprogram']
	cxxflags=ctx.env.CXXFLAGS
	if ctx.cmd in ['check']:
		features.append('test')
	if ctx.env.DEST_OS in ['linux']:
		lib.append('pthread')
	ctx.stlib(name='gtest',
		      target='../gtest',
		      source='gtest-all.cc',
		      includes='.',
		      export_includes='.')

	for subdir in SUBDIRS:
		name='%sTests'%subdir
		src=ctx.sources(path=os.path.join(ctx.path.abspath(),subdir))
		src.append('gtest_main.cc')
		ctx.program(name=name, target='../%s'%name, source=src,
			        use=['gtest','timedtext'], lib=lib, features=features,
			        defines=['private=public','protected=public'])

	ptn = re.compile('(?P<prefix>\[\s*(?P<type>\w+|=+|-+)\s*\])(?P<info>\s+.*)')
	def colourify(ctx):
		lst = getattr(ctx, 'utest_results', [])
		_cols = {
			'==========' : 'GREEN',
			'----------': 'GREEN',
			'RUN' : 'GREEN',
			'OK' : 'GREEN',
			'PASSED' : 'GREEN',
			'FAILED' : 'RED'
		}
		if lst:
			show = True if ctx.options.compact is False else False
			passed=0
			failed=0
			if not show: Logs.pprint('GREEN',"\n[==========] ", label="Running %d tests" % len(lst))
			for (f, code, out, err) in lst:
				col=''
				if code==0:
					st = '[  PASSED  ] '
					col='GREEN'
					passed+=1
				else:
					st='[  FAILED  ] '
					col='RED'
					failed+=1
				if show:
					Logs.pprint( 'CYAN' , '\nRunning tests from: %s' % f )
					for l in out.splitlines(False):
						m = re.match(ptn, l)
						if m:
							md = m.groupdict()
							Logs.pprint(_cols.get( md['type'], 'NORMAL'),
										md['prefix'], label=md['info'])
						elif not l.startswith('Running'):
							Logs.pprint('NORMAL', l)
				else:
					Logs.pprint(col,st, label=os.path.basename(f))
			if failed==0: Logs.pprint('GREEN',"[==========] ", label="Passed all tests")
			else: Logs.pprint('GREEN',"[==========] ", label="Passed %d/%d tests" %(passed, passed+failed))
			st=0 if failed==0 else 1
			sys.exit(st)
	ctx.add_post_fun(colourify)