language: cpp

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE="CheckAllOpt" BUILD="check --alltests" TESTCMD="%s" CFLAGS="-O3" CXXFLAGS="-O3" ANALYSIS="" ANALYSIS_ARGS=""
  - BUILD_TYPE="CheckAllDebug" BUILD="check --alltests" TESTCMD="%s" CFLAGS="-g -O0" CXXFLAGS="-g -O0" ANALYSIS="" ANALYSIS_ARGS=""
  - BUILD_TYPE="ScanBuild" BUILD="build" CFLAGS="-g -O0" CXXFLAGS="-g -O0" ANALYSIS="scan-build" ANALYSIS_ARGS="--status-bugs -disable-checker deadcode.DeadStores" PACKAGES="clang"
  - BUILD_TYPE="Valgrind" BUILD="check --alltests" TESTCMD="valgrind --error-exitcode=1 %s" CFLAGS="-g -O0" CXXFLAGS="-g -O0" ANALYSIS="" ANALYSIS_ARGS="" PACKAGES="valgrind"

before_install:
  - '[[ -z "${PACKAGES}" ]] || sudo apt-get -qq update'
  - '[[ -z "${PACKAGES}" ]] || sudo apt-get -qq install ${PACKAGES}'

script:
  - echo Running command '${ANALYSIS} ${ANALYSIS_ARGS} ./waf ${BUILD} --testcmd="${TESTCMD}"'
  - ${ANALYSIS} ./waf configure
  - ${ANALYSIS} ${ANALYSIS_ARGS} ./waf ${BUILD} --testcmd="${TESTCMD}"

notifications:
  irc: "irc.freenode.net#seneca-webvtt"
