language: cpp

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE="CheckAllOpt" BUILD="make check-all" CFLAGS="-O3" CXXFLAGS="-O3" ANALYSIS="" ANALYSIS_ARGS=""
  - BUILD_TYPE="CheckAllDebug" BUILD="make check-all" CFLAGS="-g -O0" CXXFLAGS="-g -O0" ANALYSIS="" ANALYSIS_ARGS=""
  #- BUILD_TYPE="clang++ ScanBuild" BUILD="make check-all" CC="clang" CXX="clang++" CFLAGS="-g -O0" CXXFLAGS="-O3" ANALYSIS="scan-build" ANALYSIS_ARGS="-v -v -k" PACKAGES="clang"

before_install:
  - '[[ -z "${PACKAGES}" ]] || sudo apt-get -qq update'
  - '[[ -z "${PACKAGES}" ]] || sudo apt-get -qq install ${PACKAGES}'

script:
  - ${ANALYSIS} ./configure
  - ${ANALYSIS} ${ANALYSIS_ARGS} ${BUILD}

notifications:
  irc: "irc.freenode.net#seneca-webvtt"
